# https://taskfile.dev

version: '3'

tasks:
  install:
    desc: Install dependencies
    run: once
    cmds:
      - poetry install
  update:
    desc: Update dependencies
    cmds:
      - poetry update
  clean:
    desc: Clean up
    cmds:
      - rm -f output.txt
      - rm -f *.db*
  setup.year:
    desc: Setup for the year
    cmds:
      - |
        for day in $(seq -w 1 25); do
          task setup.day DAY=$day YEAR={{.YEAR}}
        done
    requires:
      vars: [ YEAR ]
  setup.day:
    desc: Setup for the day
    status:
      - |
        [ -f "{{.NAME}}.ipynb" ]
    cmds:
      - mkdir -p "{{.YEAR}}"
      - cat template.ipynb | sed "s/<<DAY>>/{{.DAY}}/g" | sed "s/<<YEAR>>/{{.YEAR}}/g" > "{{.NAME}}.ipynb"
      - git add "{{.NAME}}.ipynb"
    vars:
      NAME: "{{.YEAR}}/day_{{.DAY}}"
    requires:
      vars: [ DAY, YEAR ]
  setup.today:
    desc: Setup for today
    cmds:
      - task: setup.day
        vars:
          DAY:
            sh: date "+%d"
          YEAR:
            sh: date "+%Y"
  day.run.all:
    desc: Run all days
    dir: "{{.YEAR}}"
    cmds:
      - |
        for i in day_*.ipynb; do
          jupyter execute --inplace $i;
        done
    requires:
      vars: [ YEAR ]

