name: Prep Notebook

on:
  schedule:
    - cron: '0 4 1-25 12 *' # This will run the workflow every day at 5am
  push:
    branches:
      - master
    paths:
      - '.github/workflows/prep-day.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:
  prep-notebook:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install Task
        run: pip install go-task-bin

      - name: Prepare Notebook
        run: task setup.today

      - uses: stefanzweifel/git-auto-commit-action@v6
        continue-on-error: true
        id: auto-commit-action
        with:
          commit_message: 'Preparing Notebook'
          commit_options: '--no-verify'