name: Prep Notebook

on:
  schedule:
    - cron: '0 4 1-25 12 *' # This will run the workflow every day at 5am
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:
  prep-notebook:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      - name: Install Tools
        uses: eveenendaal/github-actions/actions/install-my-tools@master
        with:
          include: task,uv

      - name: Prepare Notebook
        run: task setup.today

      - uses: stefanzweifel/git-auto-commit-action@v6
        continue-on-error: true
        id: auto-commit-action
        with:
          commit_message: 'Preparing Notebook'
          commit_options: '--no-verify'